[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
autoconfirm = true
disable_signup = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false